name: Build and Release

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    name: Build Linux ARM64 Binary
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build for Linux ARM64
      run: |
        dotnet publish -c Release -r linux-arm64 --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish/
          
    - name: Create artifact archive
      run: |
        cd publish
        tar -czf ../ghostradio-linux-arm64.tar.gz GhostRadio stations.json static.wav
        cd ..
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghostradio-linux-arm64
        path: ghostradio-linux-arm64.tar.gz
        retention-days: 30
        
    - name: Get short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-${{ steps.vars.outputs.sha_short }}
        release_name: Build ${{ github.run_number }}
        body: |
          Automated release from commit ${{ github.sha }}
          
          Changes in this build:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ghostradio-linux-arm64.tar.gz
        asset_name: ghostradio-linux-arm64.tar.gz
        asset_content_type: application/gzip