name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build Linux ARM64 Binary
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build for Linux ARM64
      run: |
        dotnet publish -c Release -r linux-arm64 --self-contained true \
          -p:PublishSingleFile=true \
          -p:PublishTrimmed=true \
          -p:TrimMode=partial \
          -o ./publish/
          
    - name: Create artifact archive
      run: |
        cd publish
        tar -czf ../ghostradio-linux-arm64.tar.gz GhostRadio stations.json static.wav
        cd ..
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ghostradio-linux-arm64
        path: ghostradio-linux-arm64.tar.gz
        retention-days: 30
        
    - name: Release binaries
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ghostradio-linux-arm64.tar.gz
        asset_name: ghostradio-linux-arm64.tar.gz
        asset_content_type: application/gzip